package com.musekeys.midi;

public class GMInstruments {
    public static String[] Instruments = {
            "Acoustic Grand Piano",
            "Bright Acoustic Piano",
            "Electric Grand Piano",
            "Honky-tonk Piano",
            "Electric Piano 1",
            "Electric Piano 2",
            "Harpsichord",
            "Clavi",
            "Celesta",
            "Glockenspiel",
            "Music Box",
            "Vibraphone",
            "Marimba",
            "Xylophone",
            "Tubular Bells",
            "Dulcimer",
            "Drawbar Organ",
            "Percussive Organ",
            "Rock Organ",
            "Church Organ",
            "Reed Organ",
            "Accordion",
            "Harmonica",
            "Tango Accordion",
            "Acoustic Guitar (nylon)",
            "Acoustic Guitar (steel)",
            "Electric Guitar (jazz)",
            "Electric Guitar (clean)",
            "Electric Guitar (muted)",
            "Overdriven Guitar",
            "Distortion Guitar",
            "Guitar harmonics",
            "Acoustic Bass",
            "Electric Bass (finger)",
            "Electric Bass (pick)",
            "Fretless Bass",
            "Slap Bass 1",
            "Slap Bass 2",
            "Synth Bass 1",
            "Synth Bass 2",
            "Violin",
            "Viola",
            "Cello",
            "Contrabass",
            "Tremolo Strings",
            "Pizzicato Strings",
            "Orchestral Harp",
            "Timpani",
            "String Ensemble 1",
            "String Ensemble 2",
            "SynthStrings 1",
            "SynthStrings 2",
            "Choir Aahs",
            "Voice Oohs",
            "Synth Voice",
            "Orchestra Hit",
            "Trumpet",
            "Trombone",
            "Tuba",
            "Muted Trumpet",
            "French Horn",
            "Brass Section",
            "SynthBrass 1",
            "SynthBrass 2",
            "Soprano Sax",
            "Alto Sax",
            "Tenor Sax",
            "Baritone Sax",
            "Oboe",
            "English Horn",
            "Bassoon",
            "Clarinet",
            "Piccolo",
            "Flute",
            "Recorder",
            "Pan Flute",
            "Blown Bottle",
            "Shakuhachi",
            "Whistle",
            "Ocarina",
            "Lead 1 (square)",
            "Lead 2 (sawtooth)",
            "Lead 3 (calliope)",
            "Lead 4 (chiff)",
            "Lead 5 (charang)",
            "Lead 6 (voice)",
            "Lead 7 (fifths)",
            "Lead 8 (bass + lead)",
            "Pad 1 (new age)",
            "Pad 2 (warm)",
            "Pad 3 (polysynth)",
            "Pad 4 (choir)",
            "Pad 5 (bowed)",
            "Pad 6 (metallic)",
            "Pad 7 (halo)",
            "Pad 8 (sweep)",
            "FX 1 (rain)",
            "FX 2 (soundtrack)",
            "FX 3 (crystal)",
            "FX 4 (atmosphere)",
            "FX 5 (brightness)",
            "FX 6 (goblins)",
            "FX 7 (echoes)",
            "FX 8 (sci-fi)",
            "Sitar",
            "Banjo",
            "Shamisen",
            "Koto",
            "Kalimba",
            "Bag pipe",
            "Fiddle",
            "Shanai",
            "Tinkle Bell",
            "Agogo",
            "Steel Drums",
            "Woodblock",
            "Taiko Drum",
            "Melodic Tom",
            "Synth Drum",
            "Reverse Cymbal",
            "Guitar Fret Noise",
            "Breath Noise",
            "Seashore",
            "Bird Tweet",
            "Telephone Ring",
            "Helicopter",
            "Applause",
            "Gunshot",
    };   
    
    public static String instrumentCategeories[]={
    		"Piano",
    		"Chromatic Percussion",
    		"Organ",
    		"Guitar",
    		"Bass",
    		"Strings",
    		"Ensemble",
    		"Brass",
    		"Reed",
    		"Pipe",
    		"Synth Lead",
    		"Synth Pad",
    		"Synth Effects",
    		"Ethnic",
    		"Percussive",
    		"Sound Effects"
    };
    
    public static String[] controllers={
    		"Bank Select",
    		"Modulation Wheel",
    		"Breath controller",
    		"Unknown controller",
    		"Foot Pedal",
    		"Portamento Time",
    		"Data Entry",
    		"Volume",
    		"Balance",
    		"Unknown controller",
    		"Pan position",
    		"Expression",
    		"Effect Control 1",
    		"Effect Control 2",
    		"Unknown controller",
    		"Unknown controller",
    		"General Purpose Slider 1",
    		"General Purpose Slider 2",
    		"General Purpose Slider 3",
    		"General Purpose Slider 4",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Bank Select (fine)",
    		"Modulation Wheel (fine)",
    		"Breath controller (fine)",
    		"Unknown controller",
    		"Foot Pedal (fine)",
    		"Portamento Time (fine)",
    		"Data Entry (fine)",
    		"Volume (fine)",
    		"Balance (fine)",
    		"Unknown controller",
    		"Pan position (fine)",
    		"Expression (fine)",
    		"Effect Control 1 (fine)",
    		"Effect Control 2 (fine)",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Hold Pedal (on/off)",
    		"Portamento (on/off)",
    		"Sustenuto Pedal (on/off)",
    		"Soft Pedal (on/off)",
    		"Legato Pedal (on/off)",
    		"Hold 2 Pedal (on/off)",
    		"Sound Variation",
    		"Sound Timbre",
    		"Sound Release Time",
    		"Sound Attack Time",
    		"Sound Brightness",
    		"Sound Decay Time",
    		"Sound Vibrato Rate",
    		"Sound Vibrato Depth",
    		"Sound Vibrato Delay",
    		"Sound Control 10",
    		"General Purpose Button 1 (on/off)",
    		"General Purpose Button 2 (on/off)",
    		"General Purpose Button 3 (on/off)",
    		"General Purpose Button 4 (on/off)",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Effects Level",
    		"Tremolo Level",
    		"Chorus Level",
    		"Celeste Level",
    		"Phaser Level",
    		"Data Button increment",
    		"Data Button decrement",
    		"Non-registered Parameter (fine)",
    		"Non-registered Parameter (coarse)",
    		"Registered Parameter (fine)",
    		"Registered Parameter (coarse)",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"Unknown controller",
    		"All Sound Off",
    		"All Controllers Off",
    		"Local Keyboard (on/off)",
    		"All Notes Off",
    		"Omni Mode Off",
    		"Omni Mode On",
    		"Mono Operation",
    		"Poly Operation"
    };
}
